# Project information
site_name: 'IoTaaP Tutorials'
site_description: 'IoTaaP Tutorials'
repo_url: 'https://github.com/iotaap/tutorials'
nav:
  - Home: index.md
  - Working Environment: working-environment.md
  - IoTaaP Cloud - MQTTS: iotaap-cloud-mqtt.md
  - IoTaaP Cloud - OTA: iotaap-cloud-ota.md
  - IoTaaP Cloud - Events: iotaap-cloud-events.md
  - IoTaaP Cloud - Visualization: iotaap-cloud-visualization.md
  - IoTaaP Core - Pins: iotaap-pins.md
  - IoTaaP Core - Jumpers: iotaap-jumpers.md
  - IoTaaP Core - LED: iotaap-blinkyled.md
  - IoTaaP Core - MISC: iotaap-misc.md
  - IoTaaP Core - OLED: iotaap-oled.md
  - IoTaaP Core - Serial: iotaap-serial.md
  - IoTaaP Core - ADC: iotaap-adc.md
  - IoTaaP Core - DAC: iotaap-dac.md
  - IoTaaP Core - PWM: iotaap-pwm.md
  - IoTaaP Core - Hall: iotaap-hall.md
  - IoTaaP Core - Buzzer: iotaap-buzzer.md
  - IoTaaP Core - WiFi: iotaap-wifi.md
  - IoTaaP Core - TCP Client: iotaap-tcpclient.md
  - IoTaaP Core - TCP Server: iotaap-tcpserver.md
  - IoTaaP Core - TSL2561: iotaap-tsl2561.md
  - IoTaaP Core - MQTT: iotaap-mqtt.md
  - IoTaaP Core - MQTTS: iotaap-mqtts.md
  - Module - WS2812 LED: ws2812-module.md
  - Module - Weather: weather-module.md
  - Module - CAN: can-module.md
  - Module - Servo Motor: servo-motor-module.md
        
copyright: 'Copyright &copy; IoTaaP'

theme: 
    name: material
    palette:
        primary: 'light-blue'
        accent: 'deep-purple'
    logo: 'images/logo.png'
    favicon: 'images/favicon.png'

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iotaap
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/iotaap
      name: Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/iotaap
      name: Facebook
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCC9hU3ndh6bh-LbW3YjI98g
      name: YouTube